name: C++ CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: write


jobs:
  build-test-release:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release

    - name: Run Tests
      working-directory: ${{github.workspace}}/build
      run: ctest -C Release --output-on-failure

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Coursework-App
        path: ${{github.workspace}}/build/Release/*.exe

    - name: Prepare files for ZIP
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        mkdir ReleaseApp
        copy ${{github.workspace}}\build\Release\*.exe ReleaseApp\
      shell: cmd

    - name: Create ZIP Archive
      if: startsWith(github.ref, 'refs/tags/v')
      run: Compress-Archive -Path ReleaseApp\* -DestinationPath Coursework-App.zip

    - name: Publish GitHub Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        files: Coursework-App.zip
        generate_release_notes: true